# Generated by Django 2.0 on 2019-08-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=120)),
                ('lastname', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.CharField(max_length=22)),
                ('subscription_date', models.DateField()),
                ('end_subscription_date', models.DateField()),
                ('active', models.BooleanField()),
            ],
        ),
    ]
