# Generated by Django 2.0 on 2019-08-13 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('firstname', 'lastname', 'email')},
        ),
    ]
