# Generated by Django 2.0 on 2019-08-18 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='created_date',
            new_name='creation_date',
        ),
    ]
