# Generated by Django 2.0 on 2019-08-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190818_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('url',)},
        ),
    ]
